# Generated by Django 4.1.5 on 2023-11-30 09:25

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarWarehouseModel',
            fields=[
                ('car_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=40)),
                ('brand', models.CharField(max_length=40)),
                ('year', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('Gasoline', 'Gasoline'), ('Diseal', 'Diseal'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=20)),
                ('stock', models.CharField(choices=[('In stock', 'In Stock'), ('Out Of Stock', 'Out Of Stock')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('phone_num', models.PositiveIntegerField()),
                ('wallet_amt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mercedes_OrderModel',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Confirming', 'Confirming'), ('At Assembly', 'At Assembly'), ('Ready to Dispatch', 'Ready to Dispatch'), ('Dispatched', 'Dispatched')], max_length=40)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplyChain_app.carwarehousemodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplyChain_app.usermodel')),
            ],
        ),
    ]
