# Generated by Django 4.1.5 on 2023-12-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplyChain_app', '0002_mercedes_ordermodel_order_amt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mercedes_OrderModel',
            new_name='OrderModel',
        ),
    ]
