# Generated by Django 4.1.5 on 2023-12-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyChain_app', '0003_rename_mercedes_ordermodel_ordermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwarehousemodel',
            name='car_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
