# Generated by Django 4.1.5 on 2023-12-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyChain_app', '0005_usermodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
