# Generated by Django 4.1.5 on 2023-12-04 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supplyChain_app', '0008_alter_ordermodel_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='est_del',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
