# Generated by Django 4.1.5 on 2023-12-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplyChain_app', '0009_ordermodel_est_del'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='order_id',
            new_name='order',
        ),
    ]
