# Generated by Django 4.1.5 on 2023-12-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyChain_app', '0010_rename_order_id_ordermodel_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='order',
            new_name='order_id',
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('Confirming', 'Confirming'), ('At Assembly', 'At Assembly'), ('Ready to Dispatch', 'Ready to Dispatch'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], max_length=40),
        ),
    ]
