# Generated by Django 5.0.1 on 2024-02-01 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyChain_app', '0012_alter_usermodel_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('transaction_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplyChain_app.ordermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplyChain_app.usermodel')),
            ],
        ),
    ]
