# Generated by Django 5.0.1 on 2024-02-04 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplyChain_app', '0013_transactionmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carwarehousemodel',
            name='brand',
        ),
    ]
