# Generated by Django 5.0.1 on 2024-02-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyChain_app', '0014_remove_carwarehousemodel_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwarehousemodel',
            name='type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carwarehousemodel',
            name='fuel_type',
            field=models.CharField(choices=[('Gasoline', 'Gasoline'), ('Diseal', 'Diseal'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=100),
        ),
    ]
