# Generated by Django 5.0.1 on 2024-02-10 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyChain_app', '0015_carwarehousemodel_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('request_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplyChain_app.ordermodel')),
            ],
        ),
    ]
