# Generated by Django 5.0.1 on 2024-02-11 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyChain_app', '0016_requestmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundModel',
            fields=[
                ('refund_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('refund_amt', models.PositiveIntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplyChain_app.requestmodel')),
            ],
        ),
    ]
