# Generated by Django 5.0.1 on 2024-02-28 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyChain_app', '0018_rename_reason_requestmodel_client_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentMailModel',
            fields=[
                ('mail_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('subject', models.CharField(max_length=75)),
                ('body', models.CharField(max_length=5000)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplyChain_app.ordermodel')),
            ],
        ),
    ]
