# Generated by Django 5.0.1 on 2024-03-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyChain_app', '0021_merchantmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantmodel',
            name='remarks',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
