# Generated by Django 5.0.1 on 2024-03-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyChain_app', '0023_blockmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockmodel',
            name='block_id',
        ),
        migrations.AddField(
            model_name='blockmodel',
            name='hash',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockmodel',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
